name: CI

on:
  push:
    branches: [ main, develop, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint (non-blocking)
        run: |
          npm run -s lint || echo "Lint step did not pass or script missing; continuing"

      - name: Run unit tests
        run: |
          npx jest --config jest.config.cjs --passWithNoTests

      - name: Run RN UI smoke tests
        run: |
          npx jest --config jest.rn.config.cjs --passWithNoTests

      - name: Build web (smoke)
        run: |
          npx expo export --platform web --experimental-bundle --force || echo "Expo web export skipped in CI"

  rules-tests:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run Firestore rules tests (emulator)
        run: |
          npx firebase emulators:exec --only firestore "npx jest --config jest.rules.config.cjs --ci"




